![image.png](img/lab6.png)

Проведите двухфакторный дисперсионный анализ данных из таблицы варианта

Порядок выполнения задания
1. Определите матрицу наблюдений и введите ее элементы; определите и введите число уровней каждого фактора и вычислите объем выборки.
2. Вычислите групповые и генеральную средние.
3. Вычислите оценки дисперсии.
4. Определите для первого фактора величину Fн.
5. Найдите для первого фактора величину qF(1 - a,k,I) (решение уравнения F(x) = 1 - а для распределения Фишера F соответствующим числом степеней свободы).
6. Сравните значения Fн со значением ха и сформулируйте вывод о справедливости гипотезы На.
7. Определите для второго фактора величину Fн.
8. Найдите для второго фактора величину qF(1 - a,k,l) (решение уравнения F(x) = 1 - а для распределения Фишера F c соответствующим числом степеней свободы).
9. Если гипотеза На отклоняется, вычислите коэффициент детерминации для первого фактора.
10. Сравните значения со значением qF(1 - a, k,l) и сформулируйте вывод о справедливости гипотезы Нв
11. Если гипотеза Нв отклоняется, вычислите коэффициент детерминации для второго фактора.
12. Вычислите оценки параметров распределения исследуемой случайной величины.

In [8]:
import numpy as np
from scipy.stats import f

# Матрица наблюдений
data = np.array([
    [6.014, 7.907, 6.628, 7.882],
    [7.305, 7.514, 8.079, 8.219],
    [8.764, 8.51, 9.255, 9.773]
])

# 1. Число уровней и объем выборки
I = data.shape[0]  # Уровни фактора A (3)
J = data.shape[1]  # Уровни фактора B (4)
n = I * J  # Объем выборки (12)

print(f"Число уровней фактора A: {I}")
print(f"Число уровней фактора B: {J}")
print(f"Объем выборки: {n}")

# 2. Групповые и генеральная средние
mean_A = np.mean(data, axis=1)  # Средние по фактору A
mean_B = np.mean(data, axis=0)  # Средние по фактору B
overall_mean = np.mean(data)  # Генеральная средняя

print("\nГрупповые средние по фактору A:", mean_A)
print("Групповые средние по фактору B:", mean_B)
print("Генеральная средняя:", overall_mean)

# 3. Оценки дисперсии
# Сумма квадратов для фактора A
SS_A = J * np.sum((mean_A - overall_mean)**2)

# Сумма квадратов для фактора B
SS_B = I * np.sum((mean_B - overall_mean)**2)

# Общая сумма квадратов
SS_total = np.sum((data - overall_mean)**2)

# Сумма квадратов остатков
SS_error = SS_total - SS_A - SS_B

# Степени свободы
df_A = I - 1  # 2
df_B = J - 1  # 3
df_error = (I - 1) * (J - 1)  # 6

print("\nСтепени свободы:")
print(f"df_A: {df_A:.4f}")
print(f"df_B: {df_B:.4f}")
print(f"df_error: {df_error:.4f}")

print(f"Сумма квадратов остатков {SS_error}")

# Средние квадраты (дисперсии)
MS_A = SS_A / df_A
MS_B = SS_B / df_B
MS_error = SS_error / df_error

print("\nСумма квадратов:")
print(f"SS_A: {SS_A:.4f}")
print(f"SS_B: {SS_B:.4f}")
print(f"SS_error: {SS_error:.4f}")
print(f"SS_total: {SS_total:.4f}")

print("\nОценки дисперсии:")
print(f"MS_A: {SS_A} / {df_A}")
print(f"MS_A: {MS_A:.4f}")
print(f"MS_B: {MS_B:.4f}")
print(f"MS_error: {MS_error:.4f}")

print(f"\nMS_error: {SS_error:.4f} / {df_error:.4f}")
print(f"\nF_H для фактора A {MS_A:.4f} / {MS_error:.4f}")
# 4. F_H для фактора A
F_A = MS_A / MS_error
print(f"\nF_H для фактора A: {F_A:.4f}")

# 5. Критическое значение для фактора A
alpha = 0.05
F_crit_A = f.ppf(1 - alpha, df_A, df_error)
print(f"Критическое значение F для фактора A (qF(1-alpha, {df_A}, {df_error})): {F_crit_A:.4f}")

# 6. Вывод для фактора A
print("\nВывод для фактора A:")
if F_A > F_crit_A:
    print(f"F_H ({F_A:.4f}) > F_crit ({F_crit_A:.4f}), отвергаем H_A: фактор A влияет на результат.")
else:
    print(f"F_H ({F_A:.4f}) <= F_crit ({F_crit_A:.4f}), не отвергаем H_A: фактор A не влияет на результат.")

# 7. F_H для фактора B
F_B = MS_B / MS_error
print(f"\nF_H для фактора B: {F_B:.4f}")

# 8. Критическое значение для фактора B
F_crit_B = f.ppf(1 - alpha, df_B, df_error)
print(f"Критическое значение F для фактора B (qF(1-alpha, {df_B}, {df_error})): {F_crit_B:.4f}")

# 9. Коэффициент детерминации для фактора A (если H_A отклоняется)
if F_A > F_crit_A:
    R2_A = SS_A / SS_total
    print(f"\nКоэффициент детерминации для фактора A: {R2_A:.4f}")

# 10. Вывод для фактора B
print("\nВывод для фактора B:")
if F_B > F_crit_B:
    print(f"F_H ({F_B:.4f}) > F_crit ({F_crit_B:.4f}), отвергаем H_B: фактор B влияет на результат.")
else:
    print(f"F_H ({F_B:.4f}) <= F_crit ({F_crit_B:.4f}), не отвергаем H_B: фактор B не влияет на результат.")

# 11. Коэффициент детерминации для фактора B (если H_B отклоняется)
if F_B > F_crit_B:
    R2_B = SS_B / SS_total
    print(f"\nКоэффициент детерминации для фактора B: {R2_B:.4f}")

# 12. Оценки параметров распределения
mean_estimate = overall_mean
std_estimate = np.sqrt(MS_error)

print("\nОценки параметров распределения:")
print(f"Среднее: {mean_estimate:.4f}")
print(f"Стандартное отклонение: {std_estimate:.4f}")

Число уровней фактора A: 3
Число уровней фактора B: 4
Объем выборки: 12

Групповые средние по фактору A: [7.10775 7.77925 9.0755 ]
Групповые средние по фактору B: [7.361      7.977      7.98733333 8.62466667]
Генеральная средняя: 7.9875

Степени свободы:
df_A: 2.0000
df_B: 3.0000
df_error: 6.0000
Сумма квадратов остатков 1.782980833333312

Сумма квадратов:
SS_A: 8.0043
SS_B: 2.3958
SS_error: 1.7830
SS_total: 12.1831

Оценки дисперсии:
MS_A: 8.00428850000002 / 2
MS_A: 4.0021
MS_B: 0.7986
MS_error: 0.2972

MS_error: 1.7830 / 6.0000

F_H для фактора A 4.0021 / 0.2972

F_H для фактора A: 13.4678
Критическое значение F для фактора A (qF(1-alpha, 2, 6)): 5.1433

Вывод для фактора A:
F_H (13.4678) > F_crit (5.1433), отвергаем H_A: фактор A влияет на результат.

F_H для фактора B: 2.6874
Критическое значение F для фактора B (qF(1-alpha, 3, 6)): 4.7571

Коэффициент детерминации для фактора A: 0.6570

Вывод для фактора B:
F_H (2.6874) <= F_crit (4.7571), не отвергаем H_B: фактор B не влияет на р

In [11]:
import numpy as np
from scipy.stats import f

# 1. Определение матрицы наблюдений и параметров
data = np.array([
    [6.014, 7.907, 6.628, 7.882],
    [7.305, 7.514, 8.079, 8.219],
    [8.764, 8.51, 9.255, 9.773]
])
a = data.shape[0]  # Уровни фактора A (строки) = 3
b = data.shape[1]  # Уровни фактора B (столбцы) = 4
n = a * b  # Объем выборки = 12
alpha = 0.05  # Уровень значимости

print("1. Матрица наблюдений:")
print(data)
print(f"Число уровней фактора A: {a}")
print(f"Число уровней фактора B: {b}")
print(f"Объем выборки: {n}")

# 2. Вычисление групповых и генеральной средних
# Генеральная средняя
general_mean = np.sum(data) / n
print("\n2. Средние:")
print(f"Генеральная средняя: {general_mean:.6f}")
print(f"Вычисление: sum(data) = {np.sum(data):.6f}, n = {n}, sum/n = {general_mean:.6f}")

# Групповые средние по фактору A (средние по строкам)
mean_A = np.mean(data, axis=1)
print("\nГрупповые средние по фактору A:")
for i in range(a):
    row_sum = np.sum(data[i, :])
    print(f"Строка {i+1}: sum = {row_sum:.6f}, mean = {row_sum/b:.6f} ({mean_A[i]:.6f})")

# Групповые средние по фактору B (средние по столбцам)
mean_B = np.mean(data, axis=0)
print("\nГрупповые средние по фактору B:")
for j in range(b):
    col_sum = np.sum(data[:, j])
    print(f"Столбец {j+1}: sum = {col_sum:.6f}, mean = {col_sum/a:.6f} ({mean_B[j]:.6f})")

# 3. Вычисление оценок дисперсии
# Общая сумма квадратов (SS_total)
SS_total = np.sum((data - general_mean) ** 2)
print("\n3. Оценки дисперсии:")
print("\nОбщая сумма квадратов (SS_total):")
for i in range(a):
    for j in range(b):
        diff = data[i, j] - general_mean
        print(f"y[{i+1},{j+1}] - mean = {data[i,j]:.6f} - {general_mean:.6f} = {diff:.6f}, squared = {diff**2:.6f}")
print(f"SS_total = {SS_total:.6f}")

# Сумма квадратов для фактора A (SS_A)
SS_A = b * np.sum((mean_A - general_mean) ** 2)
print("\nСумма квадратов для фактора A (SS_A):")
for i in range(a):
    diff = mean_A[i] - general_mean
    print(f"mean_A[{i+1}] - general_mean = {mean_A[i]:.6f} - {general_mean:.6f} = {diff:.6f}, squared = {diff**2:.6f}")
print(f"Sum of squared diffs = {np.sum((mean_A - general_mean) ** 2):.6f}")
print(f"SS_A = {b} * {np.sum((mean_A - general_mean) ** 2):.6f} = {SS_A:.6f}")

# Сумма квадратов для фактора B (SS_B)
SS_B = a * np.sum((mean_B - general_mean) ** 2)
print("\nСумма квадратов для фактора B (SS_B):")
for j in range(b):
    diff = mean_B[j] - general_mean
    print(f"mean_B[{j+1}] - general_mean = {mean_B[j]:.6f} - {general_mean:.6f} = {diff:.6f}, squared = {diff**2:.6f}")
print(f"Sum of squared diffs = {np.sum((mean_B - general_mean) ** 2):.6f}")
print(f"SS_B = {a} * {np.sum((mean_B - general_mean) ** 2):.6f} = {SS_B:.6f}")

# Остаточная сумма квадратов (SS_res)
SS_res = SS_total - SS_A - SS_B
print("\nОстаточная сумма квадратов (SS_res):")
print(f"SS_res = SS_total - SS_A - SS_B = {SS_total:.6f} - {SS_A:.6f} - {SS_B:.6f} = {SS_res:.6f}")

# Степени свободы
df_A = a - 1
df_B = b - 1
df_res = (a - 1) * (b - 1)
df_total = n - 1
print("\nСтепени свободы:")
print(f"df_A = a - 1 = {a} - 1 = {df_A}")
print(f"df_B = b - 1 = {b} - 1 = {df_B}")
print(f"df_res = (a - 1)(b - 1) = {a-1} * {b-1} = {df_res}")
print(f"df_total = n - 1 = {n} - 1 = {df_total}")

# Средние квадраты (MS)
MS_A = SS_A / df_A
MS_B = SS_B / df_B
MS_res = SS_res / df_res
print("\nСредние квадраты:")
print(f"MS_A = SS_A / df_A = {SS_A:.6f} / {df_A} = {MS_A:.6f}")
print(f"MS_B = SS_B / df_B = {SS_B:.6f} / {df_B} = {MS_B:.6f}")
print(f"MS_res = SS_res / df_res = {SS_res:.6f} / {df_res} = {MS_res:.6f}")

# 4. Величина F для фактора A
F_A = MS_A / MS_res
print("\n4. F для фактора A:")
print(f"F_A = MS_A / MS_res = {MS_A:.6f} / {MS_res:.6f} = {F_A:.6f}")

# 5. Критическое значение для фактора A
qf_A = f.ppf(1 - alpha, df_A, df_res)
print("\n5. Критическое значение для фактора A:")
print(f"qf(1 - alpha, {df_A}, {df_res}) = F(0.95, {df_A}, {df_res}) = {qf_A:.6f}")

# 6. Сравнение и вывод для фактора A
print("\n6. Вывод для гипотезы H0 (фактор A):")
if F_A > qf_A:
    print(f"F_A ({F_A:.6f}) > qf_A ({qf_A:.6f}), гипотеза H0 отклоняется.")
else:
    print(f"F_A ({F_A:.6f}) <= qf_A ({qf_A:.6f}), нет оснований отклонить H0.")

# 7. Величина F для фактора B
F_B = MS_B / MS_res
print("\n7. F для фактора B:")
print(f"F_B = MS_B / MS_res = {MS_B:.6f} / {MS_res:.6f} = {F_B:.6f}")

# 8. Критическое значение для фактора B
qf_B = f.ppf(1 - alpha, df_B, df_res)
print("\n8. Критическое значение для фактора B:")
print(f"qf(1 - alpha, {df_B}, {df_res}) = F(0.95, {df_B}, {df_res}) = {qf_B:.6f}")

# 9. Коэффициент детерминации для фактора A (если H0 отклоняется)
if F_A > qf_A:
    eta2_A = SS_A / SS_total
    print("\n9. Коэффициент детерминации для фактора A:")
    print(f"eta^2_A = SS_A / SS_total = {SS_A:.6f} / {SS_total:.6f} = {eta2_A:.6f}")
else:
    print("\n9. Коэффициент детерминации для фактора A не вычисляется, так как H0 не отклонена.")

# 10. Сравнение и вывод для фактора B
print("\n10. Вывод для гипотезы H0 (фактор B):")
if F_B > qf_B:
    print(f"F_B ({F_B:.6f}) > qf_B ({qf_B:.6f}), гипотеза H0 отклоняется.")
else:
    print(f"F_B ({F_B:.6f}) <= qf_B ({qf_B:.6f}), нет оснований отклонить H0.")

# 11. Коэффициент детерминации для фактора B (если H0 отклоняется)
if F_B > qf_B:
    eta2_B = SS_B / SS_total
    print("\n11. Коэффициент детерминации для фактора B:")
    print(f"eta^2_B = SS_B / SS_total = {SS_B:.6f} / {SS_total:.6f} = {eta2_B:.6f}")
else:
    print("\n11. Коэффициент детерминации для фактора B не вычисляется, так как H0 не отклонена.")

# 12. Оценки параметров распределения
estimated_mean = general_mean
estimated_variance = SS_total / df_total
print("\n12. Оценки параметров распределения:")
print(f"Оценка среднего: {estimated_mean:.6f}")
print(f"Оценка дисперсии: SS_total / df_total = {SS_total:.6f} / {df_total} = {estimated_variance:.6f}")

1. Матрица наблюдений:
[[6.014 7.907 6.628 7.882]
 [7.305 7.514 8.079 8.219]
 [8.764 8.51  9.255 9.773]]
Число уровней фактора A: 3
Число уровней фактора B: 4
Объем выборки: 12

2. Средние:
Генеральная средняя: 7.987500
Вычисление: sum(data) = 95.850000, n = 12, sum/n = 7.987500

Групповые средние по фактору A:
Строка 1: sum = 28.431000, mean = 7.107750 (7.107750)
Строка 2: sum = 31.117000, mean = 7.779250 (7.779250)
Строка 3: sum = 36.302000, mean = 9.075500 (9.075500)

Групповые средние по фактору B:
Столбец 1: sum = 22.083000, mean = 7.361000 (7.361000)
Столбец 2: sum = 23.931000, mean = 7.977000 (7.977000)
Столбец 3: sum = 23.962000, mean = 7.987333 (7.987333)
Столбец 4: sum = 25.874000, mean = 8.624667 (8.624667)

3. Оценки дисперсии:

Общая сумма квадратов (SS_total):
y[1,1] - mean = 6.014000 - 7.987500 = -1.973500, squared = 3.894702
y[1,2] - mean = 7.907000 - 7.987500 = -0.080500, squared = 0.006480
y[1,3] - mean = 6.628000 - 7.987500 = -1.359500, squared = 1.848240
y[1,4] - me

In [12]:
import numpy as np
from scipy.stats import f

# 1. Определение матрицы наблюдений и параметров
data = np.array([
    [6.014, 7.907, 6.628, 7.882],
    [7.305, 7.514, 8.079, 8.219],
    [8.764, 8.51, 9.255, 9.773]
])
a = data.shape[0]  # Уровни фактора A (строки) = 3
b = data.shape[1]  # Уровни фактора B (столбцы) = 4
n = a * b  # Объем выборки = 12
alpha = 0.05  # Уровень значимости

print("1. Матрица наблюдений:")
print(data)
print(f"Число уровней фактора A: {a}")
print(f"Число уровней фактора B: {b}")
print(f"Объем выборки: {n}")

# 2. Вычисление групповых и генеральной средних
general_mean = np.mean(data)
mean_A = np.mean(data, axis=1)
mean_B = np.mean(data, axis=0)

print("\n2. Средние:")
print(f"Генеральная средняя: {general_mean:.4f}")
print("Групповые средние по фактору A:", mean_A)
print("Групповые средние по фактору B:", mean_B)

# 3. Вычисление оценок дисперсии
SS_total = np.sum((data - general_mean) ** 2)
SS_A = b * np.sum((mean_A - general_mean) ** 2)
SS_B = a * np.sum((mean_B - general_mean) ** 2)
SS_res = SS_total - SS_A - SS_B

df_A = a - 1
df_B = b - 1
df_res = (a - 1) * (b - 1)
df_total = n - 1

MS_A = SS_A / df_A
MS_B = SS_B / df_B
MS_res = SS_res / df_res

print("\n3. Оценки дисперсии:")
print(f"SS_total: {SS_total:.4f}, df_total: {df_total}")
print(f"SS_A: {SS_A:.4f}, df_A: {df_A}, MS_A: {MS_A:.4f}")
print(f"SS_B: {SS_B:.4f}, df_B: {df_B}, MS_B: {MS_B:.4f}")
print(f"SS_res: {SS_res:.4f}, df_res: {df_res}, MS_res: {MS_res:.4f}")

# 4. Величина F для фактора A
F_A = MS_A / MS_res
print("\n4. F для фактора A:")
print(f"F_A: {F_A:.4f}")

# 5. Критическое значение для фактора A
qf_A = f.ppf(1 - alpha, df_A, df_res)
print("\n5. Критическое значение для фактора A:")
print(f"qf(1 - alpha, {df_A}, {df_res}): {qf_A:.4f}")

# 6. Сравнение и вывод для фактора A
print("\n6. Вывод для гипотезы H0 (фактор A):")
if F_A > qf_A:
    print(f"F_A ({F_A:.4f}) > qf_A ({qf_A:.4f}), гипотеза H0 отклоняется.")
else:
    print(f"F_A ({F_A:.4f}) <= qf_A ({qf_A:.4f}), нет оснований отклонить H0.")

# 7. Величина F для фактора B
F_B = MS_B / MS_res
print("\n7. F для фактора B:")
print(f"F_B: {F_B:.4f}")

# 8. Критическое значение для фактора B
qf_B = f.ppf(1 - alpha, df_B, df_res)
print("\n8. Критическое значение для фактора B:")
print(f"qf(1 - alpha, {df_B}, {df_res}): {qf_B:.4f}")

# 9. Коэффициент детерминации для фактора A
if F_A > qf_A:
    eta2_A = SS_A / SS_total
    print("\n9. Коэффициент детерминации для фактора A:")
    print(f"eta^2_A: {eta2_A:.4f}")
else:
    print("\n9. Коэффициент детерминации для фактора A не вычисляется, так как H0 не отклонена.")

# 10. Сравнение и вывод для фактора B
print("\n10. Вывод для гипотезы H0 (фактор B):")
if F_B > qf_B:
    print(f"F_B ({F_B:.4f}) > qf_B ({qf_B:.4f}), гипотеза H0 отклоняется.")
else:
    print(f"F_B ({F_B:.4f}) <= qf_B ({qf_B:.4f}), нет оснований отклонить H0.")

# 11. Коэффициент детерминации для фактора B
if F_B > qf_B:
    eta2_B = SS_B / SS_total
    print("\n11. Коэффициент детерминации для фактора B:")
    print(f"eta^2_B: {eta2_B:.4f}")
else:
    print("\n11. Коэффициент детерминации для фактора B не вычисляется, так как H0 не отклонена.")

# 12. Оценки параметров распределения
estimated_mean = general_mean
estimated_variance = SS_total / df_total
print("\n12. Оценки параметров распределения:")
print(f"Оценка среднего: {estimated_mean:.4f}")
print(f"Оценка дисперсии: {estimated_variance:.4f}")

1. Матрица наблюдений:
[[6.014 7.907 6.628 7.882]
 [7.305 7.514 8.079 8.219]
 [8.764 8.51  9.255 9.773]]
Число уровней фактора A: 3
Число уровней фактора B: 4
Объем выборки: 12

2. Средние:
Генеральная средняя: 7.9875
Групповые средние по фактору A: [7.10775 7.77925 9.0755 ]
Групповые средние по фактору B: [7.361      7.977      7.98733333 8.62466667]

3. Оценки дисперсии:
SS_total: 12.1831, df_total: 11
SS_A: 8.0043, df_A: 2, MS_A: 4.0021
SS_B: 2.3958, df_B: 3, MS_B: 0.7986
SS_res: 1.7830, df_res: 6, MS_res: 0.2972

4. F для фактора A:
F_A: 13.4678

5. Критическое значение для фактора A:
qf(1 - alpha, 2, 6): 5.1433

6. Вывод для гипотезы H0 (фактор A):
F_A (13.4678) > qf_A (5.1433), гипотеза H0 отклоняется.

7. F для фактора B:
F_B: 2.6874

8. Критическое значение для фактора B:
qf(1 - alpha, 3, 6): 4.7571

9. Коэффициент детерминации для фактора A:
eta^2_A: 0.6570

10. Вывод для гипотезы H0 (фактор B):
F_B (2.6874) <= qf_B (4.7571), нет оснований отклонить H0.

11. Коэффициент детерм